version: '3.8'

services:
  app:
    build: .
    container_name: laravel_api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_api_network
    depends_on:
      - redis

  webserver:
    image: nginx:alpine
    container_name: laravel_api_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_api_network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_api_redis
    restart: unless-stopped
    networks:
      - laravel_api_network
    ports:
      - "6379:6379"

networks:
  laravel_api_network:
    driver: bridge
